[package]
name = "rpi_lfa"
version = "0.1.2"
authors = ["Alexey Voznyuk <me@swizard.info>"]
description = "RaspberryPi tools for loop free architecture framework"
edition = "2018"

[dependencies]
rppal = "^0.11"
